version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: whisper-world
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p
      POSTGRES_DB: whisper_world
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
