CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO "user"
("id", "firstName", "lastName", "gender",
 "birthDate",
 "email", "password",
 "datingPreferences",
 "interests",
 "likert",
 "answers",
 "intentions",
 "lifestyle",
 "accentColor")
VALUES
    ('00000000-0000-0000-0000-000000000000', 'Alice',   'Anderson', 'male',
     '1998-02-14',
     'alice.anderson@example.com', 'password123',
     'female,male,non-binary',
     'hiking,reading,cooking',
     '{"closeness":4,"openness":4,"quietness":2}',
     '[{"cluster":"persönlichkeit","question":"Was ist dein größter Traum?","textAnswer":"Ich möchte die Welt bereisen und verschiedene Kulturen kennenlernen."},{"cluster":"beziehung","question":"Wie zeigst du Zuneigung?","textAnswer":"Durch kleine Gesten und Zeit miteinander verbringen."}]',
     'casual dating,long-term relationship',
     '{"childrenWish":"maybe","children":"no","alcohol":"sometimes","smoking":"no","cannabis":"no","politics":"center"}',
     '#FF6B6B'),

    ('00000000-0000-0000-0000-000000000001', 'Bob',     'Brown',    'female',
     '1995-07-30',
     'bob.brown@example.com',      'password123',
     'non-binary,male',
     'gaming,photography,bouldering',
     '{"closeness":5,"openness":3,"quietness":3}',
     '[{"cluster":"hobby","question":"Was machst du gerne in deiner Freizeit?","textAnswer":"Ich fotografiere gerne die Natur und spiele Videospiele."},{"cluster":"zukunft","question":"Wo siehst du dich in 5 Jahren?","textAnswer":"Hoffentlich in einer erfüllenden Beziehung mit gemeinsamen Abenteuern."}]',
     'long-term relationship',
     '{"childrenWish":"yes","children":"no","alcohol":"yes","smoking":"sometimes","cannabis":"no","politics":"left"}',
     '#4ECDC4'),

    (gen_random_uuid(), 'Charlie', 'Clark',    'non-binary',
     '2001-12-05',
     'charlie.clark@example.com',  'password123',
     'male,female',
     'music,travel,cycling',
     '{"closeness":2,"openness":2,"quietness":1}',
     '[{"cluster":"musik","question":"Welche Musik hörst du am liebsten?","textAnswer":"Indie-Rock und elektronische Musik begleiten mich täglich."},{"cluster":"reisen","question":"Was war dein schönstes Reiseerlebnis?","textAnswer":"Eine Fahrradtour durch die Alpen war unvergesslich."}]',
     'casual dating,friends',
     '{"childrenWish":"no","children":"no","alcohol":"no","smoking":"no","cannabis":"sometimes","politics":"not political"}',
     '#45B7D1'),

    (gen_random_uuid(), 'Diana',   'Davis',    'male',
     '1993-04-18',
     'diana.davis@example.com',    'password123',
     'male,female,non-binary',
     'painting,yoga,thrifting',
     '{"closeness":4,"openness":4,"quietness":1}',
     '[{"cluster":"kunst","question":"Was inspiriert dich beim Malen?","textAnswer":"Die Natur und menschliche Emotionen fließen in meine Werke ein."},{"cluster":"entspannung","question":"Wie entspannst du dich nach einem stressigen Tag?","textAnswer":"Yoga und Meditation helfen mir, zur Ruhe zu kommen."}]',
     'long-term relationship,casual dating',
     '{"childrenWish":"yes","children":"no","alcohol":"sometimes","smoking":"no","cannabis":"no","politics":"left-center"}',
     '#F39C12'),

    (gen_random_uuid(), 'Ethan',   'Evans',    'female',
     '1999-11-11',
     'ethan.evans@example.com',    'password123',
     'non-binary,female',
     'running,chess,cooking',
     '{"closeness":1,"openness":4,"quietness":5}',
     '[{"cluster":"sport","question":"Warum läufst du gerne?","textAnswer":"Laufen gibt mir Klarheit und hilft beim Stressabbau."},{"cluster":"kochen","question":"Was kochst du am liebsten?","textAnswer":"Ich experimentiere gerne mit asiatischen Gewürzen und Gerichten."}]',
     'long-term relationship',
     '{"childrenWish":"maybe","children":"no","alcohol":"no","smoking":"no","cannabis":"no","politics":"right-center"}',
     '#9B59B6'),

    (gen_random_uuid(), 'Fiona',   'Foster',   'non-binary',
     '1996-03-22',
     'fiona.foster@example.com',   'password123',
     'female,male',
     'gardening,board-games,swimming',
     '{"closeness":5,"openness":3,"quietness":1}',
     '[{"cluster":"natur","question":"Was bedeutet dir dein Garten?","textAnswer":"Mein Garten ist mein Rückzugsort, wo ich Frieden finde."},{"cluster":"spiele","question":"Welche Brettspiele spielst du gerne?","textAnswer":"Strategiespiele wie Siedler und Ticket to Ride sind meine Favoriten."}]',
     'casual dating,friends',
     '{"childrenWish":"no","children":"no","alcohol":"sometimes","smoking":"no","cannabis":"yes","politics":"left"}',
     '#2ECC71'),

    (gen_random_uuid(), 'George',  'Garcia',   'male',
     '2000-09-08',
     'george.garcia@example.com',  'password123',
     'non-binary',
     'soccer,tech-meetups,coffee-roasting',
     '{"closeness":1,"openness":4,"quietness":2}',
     '[{"cluster":"technologie","question":"Was fasziniert dich an der Technik?","textAnswer":"Die Möglichkeit, Probleme zu lösen und das Leben zu verbessern."},{"cluster":"kaffee","question":"Was macht einen perfekten Kaffee aus?","textAnswer":"Die richtige Röstung und Zubereitungsart machen den Unterschied."}]',
     'hookups',
     '{"childrenWish":"no","children":"no","alcohol":"yes","smoking":"no","cannabis":"sometimes","politics":"center"}',
     '#E74C3C'),

    (gen_random_uuid(), 'Hannah',  'Hill',     'female',
     '1997-01-27',
     'hannah.hill@example.com',    'password123',
     'female,male',
     'sketching,latin-dance,reading',
     '{"closeness":5,"openness":4,"quietness":3}',
     '[{"cluster":"kunst","question":"Was zeichnest du am liebsten?","textAnswer":"Portraits und Stadtansichten faszinieren mich besonders."},{"cluster":"tanz","question":"Wie fühlt sich Tanzen für dich an?","textAnswer":"Tanz ist pure Freude und ein Ausdruck meiner Seele."}]',
     'long-term relationship,short-term relationship',
     '{"childrenWish":"yes","children":"no","alcohol":"sometimes","smoking":"no","cannabis":"no","politics":"left"}',
     '#FF9FF3'),

    (gen_random_uuid(), 'Ian',     'Irwin',    'non-binary',
     '1994-05-06',
     'ian.irwin@example.com',      'password123',
     'non-binary',
     'film-making,climbing,meditation',
     '{"closeness":2,"openness":3,"quietness":1}',
     '[{"cluster":"film","question":"Was erzählst du gerne durch deine Filme?","textAnswer":"Ich möchte menschliche Geschichten und Emotionen einfangen."},{"cluster":"klettern","question":"Was liebst du am Klettern?","textAnswer":"Die Herausforderung und das Vertrauen in mich selbst."}]',
     'open to anything,friends',
     '{"childrenWish":"no","children":"no","alcohol":"no","smoking":"sometimes","cannabis":"yes","politics":"right"}',
     '#95A5A6'),

    (gen_random_uuid(), 'Julia',   'Johnson',  'male',
     '2002-10-19',
     'julia.johnson@example.com',  'password123',
     'female,male,non-binary',
     'piano,basketball,photography',
     '{"closeness":2,"openness":3,"quietness":4}',
     '[{"cluster":"musik","question":"Welche Gefühle drückst du beim Klavierspielen aus?","textAnswer":"Musik ist meine Art, Emotionen auszudrücken, die Worte nicht beschreiben können."},{"cluster":"sport","question":"Was bedeutet dir Basketball?","textAnswer":"Teamwork und der Kampfgeist motivieren mich auf und neben dem Platz."}]',
     'long-term relationship',
     '{"childrenWish":"maybe","children":"no","alcohol":"sometimes","smoking":"no","cannabis":"no","politics":"center"}',
     '#34495E');